language: python
matrix:
  include:
    - name: "Python 3.7 on Linux"
      python: 3.7
      dist: xenial

    - name: "Python 3.7 on macOS"
      os: osx
      osx_image: xcode10.2
      language: shell
      before_install: brew install libomp
      env: PATH=/Users/travis/Library/Python/3.7/bin:$PATH
    
#     - name: "Python 3.7 on Windows"
#       os: windows
#       language: shell
#       before_install: choco install python --version=3.7.4
#       env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

    - name: "Python 3.6 on Linux"
      python: 3.6
      dist: xenial

    - name: "Python 3.6 on macOS"
      os: osx
      osx_image: xcode9.3
      language: shell
      before_install: HOMEBREW_NO_AUTO_UPDATE=1 brew install libomp
      env: PATH=/Users/travis/Library/Python/3.6/bin:$PATH
    
#     - name: "Python 3.6 on Windows"
#       os: windows
#       language: shell
#       before_install: choco install python --version=3.6.8
#       env: PATH=/c/Python36:/c/Python36/Scripts:$PATH

    - name: "Python 3.5 on Linux"
      python: 3.5
      dist: xenial
    
#     - name: "Python 3.5 on Windows"
#       os: windows
#       language: shell
#       before_install: choco install python --version 3.5.4
#       env: PATH=/c/Python35:/c/Python35/Scripts:$PATH
      
install: pip3 install -r tests/travis_requirements.txt || pip3 install --user -r tests/travis_requirements.txt
script:
  - python3 --version || python --version
  - echo "import tests.travis_test" > test.py
  - coverage run --source models,examples test.py && coverage report

after_success:
  - codecov
  
